" Comments in Vimscript start with a `"`.

" If you open this file in Vim, it'll be syntax highlighted for you.

" Vim is based on Vi. Setting `nocompatible` switches from the default
" Vi-compatibility mode and enables useful Vim functionality. This
" configuration option turns out not to be necessary for the file named
" '~/.vimrc', because Vim automatically enters nocompatible mode if that file
" is present. But we're including it here just in case this config file is
" loaded some other way (e.g. saved as `foo`, and then Vim started with
" `vim -u foo`).
set nocompatible

" Turn on syntax highlighting.
syntax on

" Disable the default Vim startup message.
set shortmess+=I

" Show line numbers.
set number

" This enables relative line numbering mode. With both number and
" relativenumber enabled, the current line shows the true line number, while
" all other lines (above and below) are numbered relative to the current line.
" This is useful because you can tell, at a glance, what count is needed to
" jump up or down to a particular line, by {count}k to go up or {count}j to go
" down.
set relativenumber

" Always show the status line at the bottom, even if you only have one window open.
set laststatus=2

" The backspace key has slightly unintuitive behavior by default. For example,
" by default, you can't backspace before the insertion point set with 'i'.
" This configuration makes backspace behave more reasonably, in that you can
" backspace over anything.
set backspace=indent,eol,start

" By default, Vim doesn't let you hide a buffer (i.e. have a buffer that isn't
" shown in any window) that has unsaved changes. This is to prevent you from "
" forgetting about unsaved changes and then quitting e.g. via `:qa!`. We find
" hidden buffers helpful enough to disable this protection. See `:help hidden`
" for more information on this.
set hidden

" This setting makes search case-insensitive when all characters in the string
" being searched are lowercase. However, the search becomes case-sensitive if
" it contains any capital letters. This makes searching more convenient.
set ignorecase
set smartcase

" Enable searching as you type, rather than waiting till you press enter.
set incsearch

" Unbind some useless/annoying default key bindings.
nmap Q <Nop> " 'Q' in normal mode enters Ex mode. You almost never want this.

" Disable audible bell because it's annoying.
set noerrorbells visualbell t_vb=

" Enable mouse support. You should avoid relying on this too much, but it can
" sometimes be convenient.
set mouse+=a

" Try to prevent bad habits like using the arrow keys for movement. This is
" not the only possible bad habit. For example, holding down the h/j/k/l keys
" for movement, rather than using more efficient movement commands, is also a
" bad habit. The former is enforceable through a .vimrc, while we don't know
" how to prevent the latter.
" Do this in normal mode...
nnoremap <Left>  :echoe "Use h"<CR>
nnoremap <Right> :echoe "Use l"<CR>
nnoremap <Up>    :echoe "Use k"<CR>
nnoremap <Down>  :echoe "Use j"<CR>
" ...and in insert mode
inoremap <Left>  <ESC>:echoe "Use h"<CR>
inoremap <Right> <ESC>:echoe "Use l"<CR>
inoremap <Up>    <ESC>:echoe "Use k"<CR>
inoremap <Down>  <ESC>:echoe "Use j"<CR>
" Set CtrlP mapping
let g:ctrlp_map = '<c-p>'
let g:ctrlp_cmd = 'CtrlP'
" 设置 Tab 自动补全
inoremap <silent><expr> <TAB> pumvisible() ? "\<C-n>" : "\<TAB>"
inoremap <silent><expr> <S-TAB> pumvisible() ? "\<C-p>" : "\<S-TAB>"
" 设置 tab 为 4 空格
set tabstop=4        " 设置 tab 键显示为 4 个空格
set shiftwidth=4     " 设置自动缩进为 4 个空格
set expandtab        " 将 Tab 键转为空格
set softtabstop=4    " 设置插入时每次按 Tab 键插入 4 个空格

" 普通模式：方块光标
let &t_EI = "\e[2 q"
" 插入模式：竖线光标
let &t_SI = "\e[6 q"
" 替换模式：下划线光标
let &t_SR = "\e[4 q"

set background=light
colorscheme PaperColor

" ====== Vim 8 的 tabout（不占用 <Tab>）======
" 向右跳出：如果光标正对 ) ] } ' " ` 之一，就连续跳过这些符号（可跳过一串）
function! s:TaboutForward() abort
  let l:line = getline('.')
  let l:c = col('.')
  let l:len = len(l:line)
  let l:moved = 0
  while l:c <= l:len && l:line[l:c-1] =~# '[)\]}\)"''`]'
    let l:c += 1
    let l:moved += 1
  endwhile
  if l:moved > 0
    return repeat("\<Right>", l:moved)
  endif
  " 不在配对符前：保持原键位（<C-l> 的默认行为）
  return "\<C-l>"
endfunction

" 向左回跳（可选）：如果左边是 ( [ { ' " ` 之一，就往左移一格
function! s:TaboutBackward() abort
  if col('.') > 1 && getline('.')[col('.')-2] =~# '[(\[{\"''`]'
    return "\<Left>"
  endif
  " 否则保留原键（<C-j> 默认换行/映射）
  return "\<C-j>"
endfunction

" 绑定按键（不动 <Tab>）
inoremap <expr> <C-l> <SID>TaboutForward()
inoremap <expr> <C-j> <SID>TaboutBackward()
" ====== 结束 ======
set autoindent
set smartindent
set cindent
set clipboard=unnamedplus
let mapleader = " "
xnoremap <leader>c :w !clip.exe<CR>
inoremap <C-;> <Esc>A
