# 打开状态栏
set -g status on
set -g status-position bottom
set -g status 2
set -g status-justify 'left'
set -g status-interval 1
set -g status-left-length 90
set -g status-right-length 170
setw -g window-status-separator ''
set -g mode-keys vi
set -g history-limit 100000

# 插件管理器 (TPM)
set -g @plugin 'tmux-plugins/tpm'

# 推荐的美化插件
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# 主题/状态栏插件 (二选一或者都试试)
#set -g @plugin 'jimeh/tmux-themepack'
#set -g @plugin 'gpakosz/.tmux'   # oh-my-tmux 配置合集

# 状态栏样式
set -g status-bg default
set -g status-style bg=black,fg=default
setw -g window-status-format '#[fg=#c5c8c6,bg=black] #W '
setw -g window-status-current-format '#[fg=#b294bb,bg=black,bold] #W '
setw -g window-status-activity-style bg=black
setw -g window-status-bell-style bg=black

set-option -g status-left '#{S:#{?#{==:#{session_name},#{client_session}},#[fg=#1d1f21#,bg=#b294bb#,bold] #{session_name} #[fg=#b294bb#,bg=black#,nobold],#[fg=#c5c8c6#,bg=#373b41] #{session_name} #[fg=#373b41#,bg=black]}}'
set-option -g status-right '#[fg=#b294bb,bg=black]#[fg=#1d1f21,bg=#b294bb,bold] #H '
set-option -g "status-format[0]" '#[bg=#232530,fill=#232530]#{S:#{?#{==:#{session_name},#{client_session}},#[fg=#b294bb]━━━━━━━━━━━━━━━━━━━━━━━━,#[fg=#315d84]━━━━━━━━━━━━━━━━━━━━━━━━}}#[default]'
set-option -g "status-format[1]" '#[bg=black,fill=black]#[align=left range=left #{E:status-left-style}]#[push-default]#{T;=/#{status-left-length}:status-left}#[pop-default]#[norange default]#[list=on align=#{status-justify}]#[list=left-marker]<#[list=right-marker]>#[list=on]#{W:#[range=window|#{window_index} #{E:window-status-style}#{?#{&&:#{window_last_flag},#{!=:#{E:window-status-last-style},default}}, #{E:window-status-last-style},}#{?#{&&:#{window_bell_flag},#{!=:#{E:window-status-bell-style},default}}, #{E:window-status-bell-style},#{?#{&&:#{||:#{window_activity_flag},#{window_silence_flag}},#{!=:#{E:window-status-activity-style},default}}, #{E:window-status-activity-style},}}]#[push-default]#{T:window-status-format}#[pop-default]#[norange default]#{?loop_last_flag,,#{E:window-status-separator}},#[range=window|#{window_index} list=focus #{?#{!=:#{E:window-status-current-style},default},#{E:window-status-current-style},#{E:window-status-style}}#{?#{&&:#{window_last_flag},#{!=:#{E:window-status-last-style},default}}, #{E:window-status-last-style},}#{?#{&&:#{window_bell_flag},#{!=:#{E:window-status-bell-style},default}}, #{E:window-status-bell-style},#{?#{&&:#{||:#{window_activity_flag},#{window_silence_flag}},#{!=:#{E:window-status-activity-style},default}}, #{E:window-status-activity-style},}}]#[push-default]#{T:window-status-current-format}#[pop-default]#[norange list=on default]#{?loop_last_flag,,#{E:window-status-separator}}}#[nolist align=right range=right #{E:status-right-style}]#[push-default]#{T;=/#{status-right-length}:status-right}#[pop-default]#[norange default]'

# 键绑定为Alt+q
#set -g prefix M-q
#unbind C-b
#bind M-q send-prefix
# TPM 初始化（必须放在最后一行）
run '~/.tmux/plugins/tpm/tpm'
