# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# If you come from bash you might have to change your $PATH.

# Path to your Oh My Zsh installation.
export ZSH="${ZSH:-$HOME/.oh-my-zsh}"
export ZSH_CUSTOM="${ZSH_CUSTOM:-$ZSH/custom}"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time Oh My Zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="${ZSH_THEME:-robbyrussell}"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment one of the following lines to change the auto-update behavior
zstyle ':omz:update' mode "${DOTFILES_OMZ_UPDATE_MODE:-disabled}"  # disable automatic updates by default
# zstyle ':omz:update' mode auto      # update automatically without asking
# zstyle ':omz:update' mode reminder  # just remind me to update when it's time

# Uncomment the following line to change how often to auto-update (in days).
# zstyle ':omz:update' frequency 13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# You can also set it to another string to have that shown instead of the default red dots.
# e.g. COMPLETION_WAITING_DOTS="%F{yellow}waiting...%f"
# Caution: this setting can cause issues with multiline prompts in zsh < 5.7.1 (see #5765)
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
_dotfiles_zsh_dir="${${(%):-%N}:A:h}"
if [[ -r "$_dotfiles_zsh_dir/plugins.zsh" ]]; then
  source "$_dotfiles_zsh_dir/plugins.zsh"
else
  plugins=(git)
fi

if [[ -r "$ZSH/oh-my-zsh.sh" ]]; then
  source "$ZSH/oh-my-zsh.sh"
fi

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='nvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch $(uname -m)"

# Set personal aliases, overriding those provided by Oh My Zsh libs,
# plugins, and themes. Aliases can be placed here, though Oh My Zsh
# users are encouraged to define aliases within a top-level file in
# the $ZSH_CUSTOM folder, with .zsh extension. Examples:
# - $ZSH_CUSTOM/aliases.zsh
# - $ZSH_CUSTOM/macos.zsh
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
alias tldr="tldr -L zh"
alias ll="ls -lah"
alias mv="mv -i"
alias gs="git status"
export LS_COLORS="di=0;36"  # 将文件夹的颜色改为青色（你可以根据需要修改颜色）

if command -v locale >/dev/null 2>&1 && locale -a 2>/dev/null | command grep -qi '^en_US\.utf-8\|^en_US\.utf8'; then
  export LANG="${LANG:-en_US.UTF-8}"
  export LC_ALL="${LC_ALL:-en_US.UTF-8}"
elif command -v locale >/dev/null 2>&1 && locale -a 2>/dev/null | command grep -qi '^C\.utf-8\|^C\.utf8'; then
  export LANG="${LANG:-C.UTF-8}"
  export LC_ALL="${LC_ALL:-C.UTF-8}"
fi

if command -v man >/dev/null 2>&1 && command man --help 2>/dev/null | command grep -q -- ' -L'; then
  alias man='man -L zh_CN'
fi

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

_dotfiles_libtorch_root="${LIBTORCH_ROOT:-$HOME/pytorch_cuda/libtorch}"
if [[ -d "$_dotfiles_libtorch_root/share/cmake/Torch" ]]; then
  export Torch_DIR="${Torch_DIR:-$_dotfiles_libtorch_root/share/cmake/Torch}"
  export CMAKE_PREFIX_PATH="$Torch_DIR${CMAKE_PREFIX_PATH:+:$CMAKE_PREFIX_PATH}"
  export LD_LIBRARY_PATH="$_dotfiles_libtorch_root/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
fi
unset _dotfiles_libtorch_root

_dotfiles_conda_bin=""
for _dotfiles_conda_root in "${CONDA_ROOT:-}" "$HOME/anaconda3" "$HOME/miniconda3" "$HOME/miniforge3" "$HOME/mambaforge"; do
  [[ -n "$_dotfiles_conda_root" ]] || continue
  if [[ -x "$_dotfiles_conda_root/bin/conda" ]]; then
    _dotfiles_conda_bin="$_dotfiles_conda_root/bin/conda"
    break
  fi
done

if [[ -n "$_dotfiles_conda_bin" ]]; then
  __conda_setup="$("$_dotfiles_conda_bin" shell.zsh hook 2>/dev/null)"
  if [[ $? -eq 0 ]]; then
    eval "$__conda_setup"
  else
    _dotfiles_conda_root="${_dotfiles_conda_bin:h:h}"
    if [[ -f "$_dotfiles_conda_root/etc/profile.d/conda.sh" ]]; then
      . "$_dotfiles_conda_root/etc/profile.d/conda.sh"
    else
      path=("$_dotfiles_conda_root/bin" "${path[@]}")
    fi
  fi
  unset __conda_setup
fi
unset _dotfiles_conda_bin _dotfiles_conda_root

if command -v brew >/dev/null 2>&1; then
  eval "$(brew shellenv)"
elif [[ -x /home/linuxbrew/.linuxbrew/bin/brew ]]; then
  eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
fi

typeset -U path PATH
_dotfiles_extra_paths=()
for _dotfiles_path_dir in "$HOME/.local/bin" "$HOME/.dotnet" /usr/local/bin /usr/bin /bin; do
  [[ -d "$_dotfiles_path_dir" ]] && _dotfiles_extra_paths+=("$_dotfiles_path_dir")
done
path=("${_dotfiles_extra_paths[@]}" "${path[@]}")
unset _dotfiles_extra_paths _dotfiles_path_dir

if [[ -n "${WSL_DISTRO_NAME:-}" && -z "${DISPLAY:-}" && -n "${DOTFILES_WSL_DISPLAY:-}" ]]; then
  export DISPLAY="$DOTFILES_WSL_DISPLAY"
fi

[[ -r "$HOME/.zshrc.local" ]] && source "$HOME/.zshrc.local"
unset _dotfiles_zsh_dir

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

tar_xz() {
    local input_dir="$1"
    local output_dir="$2"

    echo "[INFO] Compress $input_dir $output_dir"
    echo "[INFO] Source dir size:"
    # du -sh "$input_dir"
    tar cf - "$input_dir" 2> /dev/null | xz -6T 48 -vv - > "$output_dir"
    echo "[INFO] Output size:"
    du -sh "${output_dir}"
}
export PATH="$HOME/.local/bin:$PATH"
