# ~/.bashrc: executed by bash(1) for non-login shells.
# shellcheck shell=bash
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# Use an available UTF-8 locale so ble.sh and the prompt symbols render
# correctly.
if command -v locale >/dev/null 2>&1 &&
   locale -a 2>/dev/null | command grep -Eqi '^en_US\.utf-?8$'; then
    export LANG=en_US.UTF-8
    export LC_ALL=en_US.UTF-8
elif command -v locale >/dev/null 2>&1 &&
     locale -a 2>/dev/null | command grep -Eqi '^C\.utf-?8$'; then
    export LANG=C.UTF-8
    export LC_ALL=C.UTF-8
fi

# Load ble.sh without attaching yet. Attaching at the end lets the rest of this
# file configure completion and the prompt first.
_dotfiles_blesh=""
for _dotfiles_blesh_candidate in \
    "$HOME/.local/share/blesh/ble.sh" \
    /usr/local/share/blesh/ble.sh \
    /usr/share/blesh/ble.sh; do
    if [ -r "$_dotfiles_blesh_candidate" ]; then
        _dotfiles_blesh="$_dotfiles_blesh_candidate"
        break
    fi
done
if [ -n "$_dotfiles_blesh" ]; then
    # shellcheck disable=SC1090
    source -- "$_dotfiles_blesh" --attach=none
fi
unset _dotfiles_blesh _dotfiles_blesh_candidate

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color|*-256color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
#force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	# We have color support; assume it's compliant with Ecma-48
	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
	# a case would tend to support setf rather than setaf.)
	color_prompt=yes
    else
	color_prompt=
    fi
fi

if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# colored GCC warnings and errors
#export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi
########################################
# Custom additions (from zshrc port)
########################################

export TLDR_LANGUAGE=zh
alias tldr="tldr -L zh"

if command -v man >/dev/null 2>&1 &&
   command man --help 2>/dev/null | command grep -q -- ' -L'; then
    alias man='man -L zh_CN'
fi

alias ll="ls -lah"
alias mv="mv -i"
alias gs="git status"

export LS_COLORS="di=0;36"

export NVM_DIR="$HOME/.nvm"
if [ -s "$NVM_DIR/nvm.sh" ]; then
  # shellcheck disable=SC1090
  . "$NVM_DIR/nvm.sh"
fi
if [ -s "$NVM_DIR/bash_completion" ]; then
  # shellcheck disable=SC1090
  . "$NVM_DIR/bash_completion"
fi

# User-local programs, including zsh installed by this dotfiles repository.
case ":$PATH:" in
  *":$HOME/.local/bin:"*) ;;
  *) export PATH="$HOME/.local/bin:$PATH" ;;
esac

# Initialize Conda when it is installed in one of the common user locations.
_dotfiles_conda_bin=""
for _dotfiles_conda_root in \
    "${CONDA_ROOT:-}" \
    "$HOME/anaconda3" \
    "$HOME/miniconda3" \
    "$HOME/miniforge3" \
    "$HOME/mambaforge"; do
    [ -n "$_dotfiles_conda_root" ] || continue
    if [ -x "$_dotfiles_conda_root/bin/conda" ]; then
        _dotfiles_conda_bin="$_dotfiles_conda_root/bin/conda"
        break
    fi
done
if [ -z "$_dotfiles_conda_bin" ]; then
    _dotfiles_conda_bin="$(type -P conda 2>/dev/null || true)"
fi

if [ -n "$_dotfiles_conda_bin" ]; then
    if __conda_setup="$("$_dotfiles_conda_bin" shell.bash hook 2>/dev/null)"; then
        eval "$__conda_setup"
    else
        _dotfiles_conda_root="${_dotfiles_conda_bin%/bin/conda}"
        if [ -f "$_dotfiles_conda_root/etc/profile.d/conda.sh" ]; then
            # shellcheck disable=SC1090
            . "$_dotfiles_conda_root/etc/profile.d/conda.sh"
        else
            export PATH="$_dotfiles_conda_root/bin:$PATH"
        fi
    fi
    unset __conda_setup
fi
unset _dotfiles_conda_bin _dotfiles_conda_root

# The prompt renders Conda itself to keep the layout stable when environments
# change. Conda activation still works; it just doesn't rewrite PS1.
export CONDA_CHANGEPS1=false

__dotfiles_conda_prompt() {
    local environment="${CONDA_DEFAULT_ENV:-}"
    [ -n "$environment" ] || return
    printf '(%s) ' "${environment##*/}"
}

__dotfiles_git_prompt() {
    local branch
    local state="✔"

    branch="$(command git symbolic-ref --quiet --short HEAD 2>/dev/null)" ||
        branch="$(command git rev-parse --short HEAD 2>/dev/null)" ||
        return

    if [ -n "$(command git status --porcelain --untracked-files=normal 2>/dev/null)" ]; then
        state="✘"
    fi
    printf ' [%s|%s]' "$branch" "$state"
}

__dotfiles_set_prompt() {
    local last_status=$?
    local status_color=32
    local status_text="✔"

    if [ -n "${BLE_VERSION:-}" ] && [ "${#BLE_PIPESTATUS[@]}" -gt 0 ]; then
        last_status="${BLE_PIPESTATUS[${#BLE_PIPESTATUS[@]} - 1]}"
    fi

    if [ "$last_status" -ne 0 ]; then
        status_color=31
        status_text="✘-$last_status"
    fi

    PS1="\[\033[33m\]\$(__dotfiles_conda_prompt)"
    PS1+="\[\033[${status_color}m\]${status_text}\[\033[0m\] "
    PS1+="\[\033[36m\]\w"
    PS1+="\[\033[35m\]\$(__dotfiles_git_prompt)\[\033[0m\]"
    PS1+="\n\[\033[90m\]\A\[\033[0m\] \\\$ "
}

PROMPT_COMMAND=__dotfiles_set_prompt

if [ -n "${BLE_VERSION:-}" ]; then
    bleopt complete_auto_complete=1
    bleopt complete_auto_history=1
    bleopt complete_auto_delay=150
    ble-attach
fi
